[env:xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
upload_speed = 921600
; upload_port = COM3   ← デバイスマネージャーで確認した番号に変更してコメントアウトを外す
build_flags =
    -DCORE_DEBUG_LEVEL=3
